name: Sonar Analysis CLI

on: ["push"]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

jobs:
  codacy-analysis-cli:
    name: Sonar Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v1.6
        
