name: Sonar Analysis CLI 

on: ["push"]

jobs:
  codacy-analysis-cli:
    name: Sonar Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: SonarCloud Scan
        run: sonar-scanner -X -Dsonar.login=${{ secrets.SONAR_TOKEN }}
